Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define :{{ hostname }} do |vm|
    vm.vm.box = "trusty""
    vm.vm.hostname = "{{ hostname }}"
    vm.vm.network "forwarded_port", guest: 80, host: 8080
  end

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
    libvirt.cpus = 2
    libvirt.volume_cache = 'none'
    libvirt.kernel = '{{ target }}/linux'
    libvirt.initrd = '{{ target }}/initrd.gz'
    libvirt.cmd_line = '{{ cmdline }}'
  end
end
