Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define :{{ hostname }} do |vm|
    vm.xm.box = "trusty-simple"
    vm.vm.hostname = "{{ hostname }}"
  end

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
    libvirt.cpus = 2
    libvirt.video_type = 'qxl'
    libvirt.volume_cache = 'none'
  end

  config.vm.provision :salt do |salt|
    salt.minion_key = "salt/key/{{ hostname }}.pem"
    salt.minion_pub = "salt/key/{{ hostname }}.pub"
  end

end
