{% load_yaml as dns %}


server:
{% for l in dns.listen %}
  - listen: {{ l }}
{% endfor %}

log:
  - target: syslog
    any: info

key:
{% for k in dns.key %}
  - id: {{ k.id }}
  - algorithm: {{ k.algorithm|d('hmac-md5') }}
  - secret: {{ k.secret }}
{% endfor %}

acl:
{% for k in dns.key %}
  - id: {{ k.id }}
{%- if k.from is defined %}
    address: {{ k.from }}
{%- endif %}
    key: {{ k.id }}
    action: {{ k.action }}
{% endfor %}

template:
  - id: default
    storage: /var/lib/knot/unsigned
    semantic-checks: on
    acl: [{% for k in dns.key %}{{ k.id }},{% endfor %}]

  - id: signed
    storage: /var/lib/knot/signed
    dnssec-signing: on
    semantic-checks: on
    kasp-db: kasp
    acl: [{% for k in dns.key %}{{ k.id }},{% endfor %}]

  - id: slave
    storage: /var/lib/knot/slave

zone:
{% for z in dns.zones %}
  - domain: {{ z.domain }}
    template: {{ z.template|d('default') }}
    file: {{ z.file_extracted }}
  {% if z.reverse_dns is defined %}
    {% for net in z.reverse_dns %}
  - domain: {{ net.reverse_domain }}
    module: mod-synth-record/int_{{ net.little_name }}
    {% endfor %}
  {% endif %}
{% endfor %}

mod-synth-record:
{% for z in dns.zones %}
  {% if z.reverse_dns is defined %}
    {% for net in z.reverse_dns %}
  - id: int_{{ net.little_name }}
    type: reverse
    prefix: dyn-
    origin: {{ z.domain }}
    network: {{ net.network_and_mask }}
    {% endfor %}
  {% endif %}
{% endfor %}
