#!/bin/sh


if [ $# -ne 1 ]; then
    echo "usage: $0 <cert-name-base>";
    exit 1
fi

revoked=`./list-crl | grep Serial.Number | sed -re "s/[ ]+Serial.Number:.([0-9]+)/\1/g"`

if [ "$KEY_DIR" ]; then
    cd "$KEY_DIR"

    serial=`openssl x509 -in $1 -noout -text | grep Serial.Number | sed -re "s/[ ]+Serial.Number:.([0-9]+).*/\1/g"`

    if test -n $serial; then
        for a in $revoked; do
            if test $serial -eq $a; then echo "Found Serial $a"; exit 0; fi
        done
    else
        echo "Error: did not find serial in $1 certificate, could not check for revocation"
    fi
else
    echo 'Please source the vars script first (i.e. "source ./vars")'
    echo 'Make sure you have edited it to reflect your configuration.'
fi

exit 1