services:

  # group: gui
  gui:
    image: grafana/grafana:latest
    user: "472:472"
    networks:
      - metric_net
    expose:
      - "3000"
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning:ro
      - grafana:/var/lib/grafana
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://gui:3000/
      GF_USERS_ALLOW_SIGN_UP: "false"
      # GF_INSTALL_PLUGINS: grafana-piechart-panel,snuids-radar-panel,fatcloud-windrose-panel,digrich-bubblechart-panel,natel-discrete-panel
      # GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-piechart-panel,snuids-radar-panel,fatcloud-windrose-panel,digrich-bubblechart-panel,natel-discrete-panel
      # GF_LOG_FILTERS: rendering:debug

  renderer:
    image: grafana/grafana-image-renderer:latest
    networks:
      - metric_net
    expose:
      - "8081"
    environment:
      # ENABLE_METRICS: "true"
      IGNORE_HTTPS_ERRORS: "true"
