#!/bin/sh

. /usr/share/debconf/confmodule

set -e

anna-install parted-udeb
preseed_fetch custom-part.sh /tmp/custom-part.sh
chmod 755 /tmp/custom-part.sh

echo /tmp/custom-part.sh installer >> /var/lib/dpkg/info/download-installer.postinst

