services:

  # group metric:exporter
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /:/host:ro,rslave
      - /app/etc/metric_import:/etc/metric_import
    options:
      - --net host
      - --pid host
      - --cap-add=SYS_TIME
    args:
      - --web.listen-address {{ salt['pillar.get']('docker:ip') }}:9100
      - --path.rootfs /host
      - --collector.textfile.directory /var/lib/metric_import
      - --no-collector.arp
      - --no-collector.bcache
      - --no-collector.conntrack
      - --no-collector.sockstat

  mtail_exporter:
    image:
    can make: postfix and some others, see example

  postgres_exporter:
    image: wrouesnel/postgres_exporter
    args:
      - -p {{ salt['pillar.get']('docker:ip') }}:9187:9187
      - -e DATA_SOURCE_NAME=${DATABASE_URL}

  mysql_exporter:

  redis_exporter:

  indluxdb_exporter:

  # more static prometheus config for for eg. spamd, podman and probably many others
