# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|

  config.vm.box = "trusty"
  config.vm.hostname = "{{ hostname }}"
  config.vm.provider "libvirt" do |lv|
    lv.memory = 512
    lv.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo mkdir -p /etc/salt
    sudo cp /vagrant/minion_id /etc/salt/
  SHELL

  config.vm.provision :salt do |salt|
    salt.minion_pub = "{{ fqdn }}.pub"
    salt.minion_key = "{{ fqdn }}.pem"
    salt.run_highstate = true
  end

end
