# -*- mode: ruby -*-
# vi: set ft=ruby :

# requires vagrant-berkself and vagrant-omnibus plugins

{% set mysql_root= salt['cmd.run_stdout']('pwgen 12 1') %}
{% set mysql_repl= salt['cmd.run_stdout']('pwgen 12 1') %}
{% set mysql_debian= salt['cmd.run_stdout']('pwgen 12 1') %}
{% set postgres_root= salt['cmd.run_stdout']('pwgen 12 1') %}
{% set admin_pass= salt['cmd.run_stdout']('pwgen 12 1') %}


Vagrant.configure("2") do |config|
  config.vm.hostname = "owcloud"

  config.vm.box = "precise"

  #config.vm.network :forwarded_port, guest: 80, host: 8080
  #config.vm.network :forwarded_port, guest: 443, host: 8443
  #config.vm.network :public_network, :dev => "br1", :mode => "bridge" 

  config.berkshelf.enabled = true
  config.omnibus.chef_version = :latest
  #config.vm.provision :shell, :inline => "curl -L https://www.opscode.com/chef/install.sh | sudo bash --"

  config.vm.provision :chef_solo do |chef|
    chef.run_list = [
      "recipe[owncloud::default]"
    ]
    chef.json = {
      "mysql" => {
        "server_root_password" => "{{ mysql_root }}",
        "server_repl_password" => "{{ mysql_repl }}",
        "server_debian_password" => "{{ mysql_debian }}"
      },
      "postgresql" => {
        "password" => {
          "postgres" => "{{ postgres_root }}"
        }
      },
      "owncloud" => {
        "version" => "6.0.0a",
        "admin" => {
          "pass" => "{{ admin_pass }}"
        },
        "config" => {
          "dbpassword" => "{{ postgres_root }}",
          "dbtype" => "postgresql"
        }
      }
    }
  end
end
