
networks:
  assistant_net:

volumes:
  mosquitto:
  zigbee2mqtt:
  hass:
  appdaemon:
  rhasspy:

services:

  # MQTT Server
  mosquitto:
    container_name: mosquitto
    image: docker.io/library/eclipse-mosquitto:latest
    restart: "unless-stopped"
    networks:
      - assistant_net
    # ports: []
      # default: mqtt: 1883 (plaintext)
      # optional: mqtts: 8883 (tls)
      # - localhost:1883:1883
      # - 8883:8883
    volumes:
      - mosquitto:/mosquitto/data
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  # bridges Zigbee events and controls Zigbee devices via MQTT
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: docker.io/koenkk/zigbee2mqtt:latest
    restart: "unless-stopped"
    environment:
      ZB_ADAPTER: /dev/ttyUSB0
      ZB_RUNAS: "1001"
    networks:
      - assistant_net
    # ports: []
      # default frontend: 8080
      # - 8080:8080
    volumes:
      - zigbee2mqtt:/app/data
      - ./zigbee2mqtt/configuration.yaml:/app/data/configuration.yaml
      - ./zigbee2mqtt/devices.yaml:/app/data/devices.yaml:rw
      - ./zigbee2mqtt/groups.yaml:/app/data/groups.yaml:rw
    devices:
      - ${ZB_ADAPTER}:/dev/ttyACM0:rw
    user: ${ZB_RUNAS}:${ZB_RUNAS}
    group_add:
      - dialout
    # command: ["/sbin/tini", "--", "node", "index.js", "--unhandled-rejections=strict"]
    depends_on:
      - mosquitto

  # homeassistant connecting to zigbee devices via MQTT to zigbee2mqtt
  hass:
    container_name: hass
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: "unless-stopped"
    environment:
      HASS_RUNAS: "1001"
      PUID: $HASS_RUNAS
      PGID: $HASS_RUNAS
      # DISABLE_JEMALLOC: true
    networks:
      - assistant_net
    # user: ${HASS_RUNAS}:${HASS_RUNAS}
    # ports: []
      # - "8123:8123"
    volumes:
      - hass:/config
      - ./hass/configuration.yaml:/config/configuration.yaml
      - ./hass/run:/etc/services.d/home-assistant/run
      - ./hass/include:/config/include
      - ./hass/packages:/config/packages
      # XXX must be in sync with defaults.jinja config:hass:plural_names entries
      - ./hass/scenes.yaml:/config/scenes.yaml
      - ./hass/automations.yaml:/config/automations.yaml
      - ./hass/sensors.yaml:/config/sensors.yaml
    depends_on:
      - mosquitto
      - zigbee2mqtt
