kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: skooner
  namespace: kube-system
spec:
  rules:
  -
    host: skooner.zap.lan
    http:
      paths:
      -
        path: /
        backend:
          serviceName: skooner
          servicePort: 80
