# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "subsonic"
  config.vm.box = "precise"

  # require `vagrant plugin install vagrant-berkshelf`
  config.berkshelf.enabled = true

  # require `vagrant plugin install vagrant-omnibus`
  config.omnibus.chef_version = :latest
  config.vm.provision :shell, :inline => "echo 'export DEBIAN_FRONTEND=noninteractive; apt-get -y update; apt-get -y install acpid build-essential' | sudo bash"

  config.vm.provision :chef_solo do |chef|
    chef.json = {
      :mysql => {
        :server_root_password => 'rootpass',
        :server_debian_password => 'debpass',
        :server_repl_password => 'replpass'
      },
      'tt-rss' => {
        'download-url' => 'https://github.com/gothfox/Tiny-Tiny-RSS/archive/1.9.tar.gz'
      }
    }

    chef.run_list = [
        "recipe[ttrss::default]"
    ]
  end

end
