# -*- mode: ruby -*-
# vi: set ft=ruby :

## The default Bookie repo that will be cloned if you don't
## already have an instance of Bookie in this directory.
BOOKIE_REPO = "https://github.com/mitechie/Bookie.git"

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = "bookie"
  config.vm.box     = "ubuntu1204"

  ## Setup port forwarding
  #config.vm.network :forwarded_port, guest: 6543, host: 6543
  #config.vm.network :public_network, :dev => "br1", :mode => "bridge" 

  ## Configure the VM with more memory
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
    libvirt.cpus = 2
  end

  ## Provision
  config.vm.provision "shell", inline: "sudo apt-get update"
  config.vm.provision "shell", inline: "sudo apt-get install -y build-essential git"
  config.vm.provision "shell", inline: "[ ! -d /vagrant/Bookie ] && git clone #{BOOKIE_REPO} /vagrant/Bookie || echo 'Repo exists. Skipping.'"
  config.vm.provision "shell", inline: "cd /vagrant/Bookie && NONINTERACTIVE=true make sysdeps && make install && make run"
end
