#!/bin/bash
#echo "$@" >> /tmp/test2.out

extension=""
dest=$4
if test "${dest:0:8}" == "archive_"; then
    dest="${dest#archive_}"
    if test "${dest: -12:12}" = "spitzauer.at"; then
        extension="public/${dest%@spitzauer.at}"
    fi
fi

if test "$extension" == ""; then
    #echo "/usr/lib/dovecot/dovecot-lda $@/`date +%Y`" >> /tmp/test2.out
    /usr/lib/dovecot/dovecot-lda $@/`date +%Y`
else
    #echo "/usr/lib/dovecot/dovecot-lda $@ $extension/`date +%Y`" >> /tmp/test2.out
    /usr/lib/dovecot/dovecot-lda $@ $extension/`date +%Y`
fi
