#!/bin/bash
#echo "$@" >> /tmp/test1.out

extension=""
dest=$4
if test "${dest:0:8}" == "archive_"; then
    dest="${dest#archive_}"
    if test "${dest: -12:12}" = "spitzauer.at"; then
        extension="public/${dest%@spitzauer.at}"
    fi
fi

#echo "/usr/lib/dovecot/dovecot-lda $@ $extension" >> /tmp/test1.out
/usr/lib/dovecot/dovecot-lda $@ $extension

