# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|

  config.vm.box = "vivid"
  config.vm.hostname = "vivid-mate"
  config.vm.provider "libvirt" do |lv|
    lv.memory = 2048
    lv.cpus = 2
    lv.graphics_type = "spice"
    lv.video_type = "qxl"
    lv.video_vram = 65536
  end

  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    if test -f /vagrant/02proxy; then cp /vagrant/02proxy /etc/apt/apt.conf.d/; fi
    sed -ire 's/^.*GRUB_CMDLINE_LINUX=.*/GRUB_CMDLINE_LINUX="nosplash nomodeset"/g' /etc/default/grub
    export DEBIAN_FRONTEND=noninteractive
    apt-get -y update
    apt-get -y install software-properties-common spice-vdagent
    apt-add-repository -y ppa:ubuntu-mate-dev/ppa
    apt-add-repository -y ppa:ubuntu-mate-dev/vivid-mate
    apt-get -y update
    apt-get -y upgrade
    apt-get -y install ubuntu-mate-core ubuntu-mate-desktop
    apt-get -y install --no-install-recommends indicator-application-gtk2 indicator-sound-gtk2 mate-indicator-applet
  SHELL

end
