# before: librarian-chef install

environments: &environments
  production: &production
    attributes: &attributes
      redmine:
        git_revision: '2.3.4'
        db:
          rails_env: production
      mysql:
        server_root_password: 'root'
        server_debian_password: 'root'
        server_repl_password: 'root'
    run_list: &run_list
      - apt::default
      - redmine::dependencies
      - redmine::default
      - redmine::database
      - redmine::nginx
    nodes:
      vagrant:
        host: 10.0.0.10
        user: vagrant
        password: vagrant
        vagrant: { IP: 10.0.0.10 } # gusteau chokes if you don't specify IP for vagrant VM

