# Mind the indentation.
#
# Uncomment the following to setup production-test1:
#
environments:
  <<: *environments
  production:
    attributes: *attributes
    run_list: *run_list
    nodes:
      vagrant: 
        attributes:
          redmine: { db: { rails_env: production } }
