# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Options for libvirt vagrant provider.
  config.vm.provider :libvirt do |libvirt|

    # A hypervisor name to access. Different drivers can be specified, but
    # this version of provider creates KVM machines only. Some examples of
    # drivers are qemu (KVM/qemu), xen (Xen hypervisor), lxc (Linux Containers),
    # esx (VMware ESX), vmwarews (VMware Workstation) and more. Refer to
    # documentation for available drivers (http://libvirt.org/drivers.html).
    libvirt.driver = "kvm"

    # The name of the server, where libvirtd is running.
    #libvirt.host = "localhost"

    # If use ssh tunnel to connect to Libvirt.
    #libvirt.connect_via_ssh = false

    # The username and password to access Libvirt. Password is not used when
    # connecting via ssh.
    #libvirt.username = "root"
    #libvirt.password = "secret"

    #libvirt.socket = "/var/run/libvirt/libvirt-sock"

    # overrides above
    libvirt.uri = "qemu:///system"
    
    # Libvirt storage pool name, where box image and instance snapshots will
    # be stored.
    libvirt.storage_pool_name = "default"

    # do not cache i/o
    libvirt.volume_cache = "none"

  end
end

