#!/bin/bash


usage() {
    cat <<EOF
Usage: $0 sourcefile lvmvolumename size [virt-resize opt]+

EOF
exit 1

}
if test "$1" == "help" -o "$1" == "--help" -o "$1" == "?" -o "$1" == "-?"; then usage; fi
if test "$1" == ""; then usage; fi
if test "$2" == ""; then usage; fi
if test "$3" == ""; then usage; fi
if test "$4" == ""; then usage; fi

if test "$5" == ""; then 
    expand_lv=""
else
    expand_lv=" --LV-expand $5"
fi


sourcefile=$1; 
volumegroup="vg0"
volumename=$2
volumesize=$3
expand_pt=" --expand $4"

#lvcreate --name $volumename --size ${volumesizesize} $volumegroup
echo "virt-resize $sourcefile /dev/mapper/$volumegroup-$volumename $expand_pt $expand_lv"

virt-resize $sourcefile /dev/mapper/$volumegroup-$volumename $expand_pt $expand_lv

