#!/bin/bash


usage() {
    cat <<EOF
Usage: $0 sourceformat sourcefile lvmvolumename 

EOF
exit 1

}
if test "$1" == "help" -o "$1" == "--help" -o "$1" == "?" -o "$1" == "-?"; then usage; fi
if test "$1" == ""; then usage; fi
if test "$2" == ""; then usage; fi
if test "$3" == ""; then usage; fi
if test ! -e $2; then usage; fi

sourceformat=$1
sourcefile=$2
volumegroup=vg0
volumename=$3

virtsizeresponse=`qemu-img info "$sourcefile" | grep virtual.size`
virtsize=`echo "$virtsizeresponse" | sed -re "s/virtual.size:.[0-9.]+[KMGT].\(([0-9]+).bytes\)/\\1/g"`
echo "Size: $virtsizeresponse ($virtsize)"
lvcreate --name $volumename --size ${virtsize}b $volumegroup
for d in /sys/block/sd[a-z]/queue/scheduler; do echo "old: $d => $(cat $d)"; echo cfq > $d ; echo "new: $d => $(cat $d)"; done
# ionice needs cfq scheduler to be effectiv, we are setting 
nice -n 19 ionice -c 3 qemu-img convert -f $sourceformat -O raw $sourcefile /dev/mapper/$volumegroup-$volumename
for d in /sys/block/sd[a-z]/queue/scheduler; do echo "old: $d => $(cat $d)"; echo deadline > $d ; echo "new: $d => $(cat $d)"; done

